package com.mediconnect.entity;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    CONSULTATION_STARTED,
    CONSULTATION_COMPLETED,
    PRESCRIPTION_READY,
    RECORD_SHARED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    GENERAL
}